### PR TITLE
Created an attach point for the grabbed object.

### PR DESCRIPTION
**Pull request by WarmedxMints**
Because the rigidbodys velocity seems to be affected by the change in parent I used code from Valve's SteamVR interaction system to estimate the velocity based on previous frames.

### CODE REVIEW

**Review by Laumania — CHANGES_REQUESTED** [review]
Thanks for your PR, but I don't think this solves the issue properly. The handling is very stiff now, and the object is now an actual child of the player. If you try your version and switch back to master, you will see that the object "flows" more when you rotate thee pllayer - and that behavior needs to stay as-is.

Also, it would be nice if you kept my indentations, as it's a little hard to review now as it shows a lot of changes, that is not really code changes.

But again, thanks for your suggestion! 👍

**Comment by Laumania** [comment]
Really nice with the scrolling. There are some issues with it. Try grabbing an object scroll far out or ind, drop the object and grab another one. The object will then snap to some odd "holdposition" and when you as the player rotate, the behavior is weird too.

I set up the scrollsensitivity to 200 by the way, to move the objects quicker.

Keep up the good work, you managed to implement the other stuff while I made dinner for my kids :D

**Comment by Laumania** [comment]
Oh, and above comment was for @WarmedxMints of cause, don't know if you get notifications if I don't tag you.

**Comment by WarmedxMints** [comment]
I've changed the way the grabbed object movement via the scrollwheel is applied which should fix the rotation and position issues when it is moved.

**Comment by Laumania** [comment]
Once again, this is SUPER awesome! Seems to work perfectly now :)

Now we only miss two things, as I see it right now, to mimic the Physics Gun from Garry's Mod.

1. While holding an object and clicking Right Mouse, the object is placed exactly where it is and freezed there (isKinematic = true, I guess would be the solution), and then of cause the object is released from "grabbing".

2. While holding an object, holding Shift, makes the object snap to certain angle, like 0, 45, 90 etc. i guess.

See this video, where he shows and explains how the Garry's Mod gun works.
https://youtu.be/nYSqRRHyxn4?t=129
Starts around 02:05 with manipulating objects, which is the behavior we are after here.

Let me know, if you are not up for the challenge, then I'm merge in all the good stuff you have done already, and then look at this myself.

**Comment by Laumania** [comment]
Arh again...forgot to mention you @WarmedxMints :P

**Comment by Laumania** [comment]
Once again..... 👏  just amazing :)

**Review by Laumania — APPROVED** [review]

**Pull request merged**
